<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Axxell
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * axxell-api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Axxell;

use \Axxell\Configuration;
use \Axxell\ApiClient;
use \Axxell\ApiException;
use \Axxell\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Axxell
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for aggregateCountEvents
     *
     * .
     *
     */
    public function testAggregateCountEvents()
    {

    }

    /**
     * Test case for aggregateEffective
     *
     * .
     *
     */
    public function testAggregateEffective()
    {

    }

    /**
     * Test case for aggregateEvents
     *
     * .
     *
     */
    public function testAggregateEvents()
    {

    }

    /**
     * Test case for aggregateRecent
     *
     * .
     *
     */
    public function testAggregateRecent()
    {

    }

    /**
     * Test case for aggregateTop
     *
     * .
     *
     */
    public function testAggregateTop()
    {

    }

    /**
     * Test case for authStore
     *
     * .
     *
     */
    public function testAuthStore()
    {

    }

    /**
     * Test case for deleteAllEvents
     *
     * .
     *
     */
    public function testDeleteAllEvents()
    {

    }

    /**
     * Test case for deleteAllItems
     *
     * .
     *
     */
    public function testDeleteAllItems()
    {

    }

    /**
     * Test case for deleteItem
     *
     * .
     *
     */
    public function testDeleteItem()
    {

    }

    /**
     * Test case for recommendInteresting
     *
     * .
     *
     */
    public function testRecommendInteresting()
    {

    }

    /**
     * Test case for recommendSimilar
     *
     * .
     *
     */
    public function testRecommendSimilar()
    {

    }

    /**
     * Test case for registerEvent
     *
     * .
     *
     */
    public function testRegisterEvent()
    {

    }

    /**
     * Test case for registerItem
     *
     * .
     *
     */
    public function testRegisterItem()
    {

    }

    /**
     * Test case for registerStore
     *
     * .
     *
     */
    public function testRegisterStore()
    {

    }

    /**
     * Test case for retrieveEvents
     *
     * .
     *
     */
    public function testRetrieveEvents()
    {

    }

    /**
     * Test case for retrieveItems
     *
     * .
     *
     */
    public function testRetrieveItems()
    {

    }

}
